name: planet_explorer
description: Una aplicación Flutter para explorar planetas utilizando Riverpod, go_router y arquitectura limpia.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  animate_do: ^4.2.0
  flutter_easyloading: ^3.0.5
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/img/
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo_app.png"

